theme: jekyll-theme-dinky

title: TaPP 2024
description: 16th International Workshop on Theory and Practice of Provenance

email: vanbasm@wfu.edu

plugins:
    - jekyll-seo-tag

whitelist:
    - jekyll-seo-tag

markdown: kramdown

safe: False
